//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.11 at 07:13:58 PM UZT 
//


package https.www_google_com.apis.ads.publisher.v202205;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rval">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="totalResultSetSize" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="startIndex" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="results">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="targetWindow" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="adUnitCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="inheritedAdSenseSettings">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="value">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="adSenseEnabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="borderColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="titleColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="backgroundColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="textColor" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="urlColor" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                 &lt;element name="adType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="borderStyle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="fontFamily" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="fontSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rval"
})
@XmlRootElement(name = "getAdUnitsByStatementResponse")
public class GetAdUnitsByStatementResponse {

    @XmlElement(required = true)
    protected GetAdUnitsByStatementResponse.Rval rval;

    /**
     * Gets the value of the rval property.
     * 
     * @return
     *     possible object is
     *     {@link GetAdUnitsByStatementResponse.Rval }
     *     
     */
    public GetAdUnitsByStatementResponse.Rval getRval() {
        return rval;
    }

    /**
     * Sets the value of the rval property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetAdUnitsByStatementResponse.Rval }
     *     
     */
    public void setRval(GetAdUnitsByStatementResponse.Rval value) {
        this.rval = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="totalResultSetSize" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="startIndex" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="results">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="targetWindow" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="adUnitCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="inheritedAdSenseSettings">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="value">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="adSenseEnabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="borderColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="titleColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="backgroundColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="textColor" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="urlColor" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                                       &lt;element name="adType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="borderStyle" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="fontFamily" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="fontSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "totalResultSetSize",
        "startIndex",
        "results"
    })
    public static class Rval {

        protected byte totalResultSetSize;
        protected byte startIndex;
        @XmlElement(required = true)
        protected GetAdUnitsByStatementResponse.Rval.Results results;

        /**
         * Gets the value of the totalResultSetSize property.
         * 
         */
        public byte getTotalResultSetSize() {
            return totalResultSetSize;
        }

        /**
         * Sets the value of the totalResultSetSize property.
         * 
         */
        public void setTotalResultSetSize(byte value) {
            this.totalResultSetSize = value;
        }

        /**
         * Gets the value of the startIndex property.
         * 
         */
        public byte getStartIndex() {
            return startIndex;
        }

        /**
         * Sets the value of the startIndex property.
         * 
         */
        public void setStartIndex(byte value) {
            this.startIndex = value;
        }

        /**
         * Gets the value of the results property.
         * 
         * @return
         *     possible object is
         *     {@link GetAdUnitsByStatementResponse.Rval.Results }
         *     
         */
        public GetAdUnitsByStatementResponse.Rval.Results getResults() {
            return results;
        }

        /**
         * Sets the value of the results property.
         * 
         * @param value
         *     allowed object is
         *     {@link GetAdUnitsByStatementResponse.Rval.Results }
         *     
         */
        public void setResults(GetAdUnitsByStatementResponse.Rval.Results value) {
            this.results = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="targetWindow" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="adUnitCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="inheritedAdSenseSettings">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="value">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="adSenseEnabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="borderColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="titleColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="backgroundColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="textColor" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="urlColor" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                             &lt;element name="adType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="borderStyle" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="fontFamily" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="fontSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "name",
            "description",
            "targetWindow",
            "status",
            "adUnitCode",
            "inheritedAdSenseSettings"
        })
        public static class Results {

            protected short id;
            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String description;
            @XmlElement(required = true)
            protected String targetWindow;
            @XmlElement(required = true)
            protected String status;
            protected int adUnitCode;
            @XmlElement(required = true)
            protected GetAdUnitsByStatementResponse.Rval.Results.InheritedAdSenseSettings inheritedAdSenseSettings;

            /**
             * Gets the value of the id property.
             * 
             */
            public short getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(short value) {
                this.id = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the targetWindow property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTargetWindow() {
                return targetWindow;
            }

            /**
             * Sets the value of the targetWindow property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTargetWindow(String value) {
                this.targetWindow = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatus() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatus(String value) {
                this.status = value;
            }

            /**
             * Gets the value of the adUnitCode property.
             * 
             */
            public int getAdUnitCode() {
                return adUnitCode;
            }

            /**
             * Sets the value of the adUnitCode property.
             * 
             */
            public void setAdUnitCode(int value) {
                this.adUnitCode = value;
            }

            /**
             * Gets the value of the inheritedAdSenseSettings property.
             * 
             * @return
             *     possible object is
             *     {@link GetAdUnitsByStatementResponse.Rval.Results.InheritedAdSenseSettings }
             *     
             */
            public GetAdUnitsByStatementResponse.Rval.Results.InheritedAdSenseSettings getInheritedAdSenseSettings() {
                return inheritedAdSenseSettings;
            }

            /**
             * Sets the value of the inheritedAdSenseSettings property.
             * 
             * @param value
             *     allowed object is
             *     {@link GetAdUnitsByStatementResponse.Rval.Results.InheritedAdSenseSettings }
             *     
             */
            public void setInheritedAdSenseSettings(GetAdUnitsByStatementResponse.Rval.Results.InheritedAdSenseSettings value) {
                this.inheritedAdSenseSettings = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="value">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="adSenseEnabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="borderColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="titleColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="backgroundColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="textColor" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="urlColor" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *                   &lt;element name="adType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="borderStyle" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="fontFamily" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="fontSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class InheritedAdSenseSettings {

                @XmlElement(required = true)
                protected GetAdUnitsByStatementResponse.Rval.Results.InheritedAdSenseSettings.Value value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link GetAdUnitsByStatementResponse.Rval.Results.InheritedAdSenseSettings.Value }
                 *     
                 */
                public GetAdUnitsByStatementResponse.Rval.Results.InheritedAdSenseSettings.Value getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link GetAdUnitsByStatementResponse.Rval.Results.InheritedAdSenseSettings.Value }
                 *     
                 */
                public void setValue(GetAdUnitsByStatementResponse.Rval.Results.InheritedAdSenseSettings.Value value) {
                    this.value = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="adSenseEnabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="borderColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="titleColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="backgroundColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="textColor" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="urlColor" type="{http://www.w3.org/2001/XMLSchema}short"/>
                 *         &lt;element name="adType" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="borderStyle" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="fontFamily" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="fontSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "adSenseEnabled",
                    "borderColor",
                    "titleColor",
                    "backgroundColor",
                    "textColor",
                    "urlColor",
                    "adType",
                    "borderStyle",
                    "fontFamily",
                    "fontSize"
                })
                public static class Value {

                    @XmlElement(required = true)
                    protected String adSenseEnabled;
                    @XmlElement(required = true)
                    protected String borderColor;
                    @XmlElement(required = true)
                    protected String titleColor;
                    @XmlElement(required = true)
                    protected String backgroundColor;
                    protected byte textColor;
                    protected short urlColor;
                    @XmlElement(required = true)
                    protected String adType;
                    @XmlElement(required = true)
                    protected String borderStyle;
                    @XmlElement(required = true)
                    protected String fontFamily;
                    @XmlElement(required = true)
                    protected String fontSize;

                    /**
                     * Gets the value of the adSenseEnabled property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getAdSenseEnabled() {
                        return adSenseEnabled;
                    }

                    /**
                     * Sets the value of the adSenseEnabled property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setAdSenseEnabled(String value) {
                        this.adSenseEnabled = value;
                    }

                    /**
                     * Gets the value of the borderColor property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getBorderColor() {
                        return borderColor;
                    }

                    /**
                     * Sets the value of the borderColor property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setBorderColor(String value) {
                        this.borderColor = value;
                    }

                    /**
                     * Gets the value of the titleColor property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTitleColor() {
                        return titleColor;
                    }

                    /**
                     * Sets the value of the titleColor property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTitleColor(String value) {
                        this.titleColor = value;
                    }

                    /**
                     * Gets the value of the backgroundColor property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getBackgroundColor() {
                        return backgroundColor;
                    }

                    /**
                     * Sets the value of the backgroundColor property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setBackgroundColor(String value) {
                        this.backgroundColor = value;
                    }

                    /**
                     * Gets the value of the textColor property.
                     * 
                     */
                    public byte getTextColor() {
                        return textColor;
                    }

                    /**
                     * Sets the value of the textColor property.
                     * 
                     */
                    public void setTextColor(byte value) {
                        this.textColor = value;
                    }

                    /**
                     * Gets the value of the urlColor property.
                     * 
                     */
                    public short getUrlColor() {
                        return urlColor;
                    }

                    /**
                     * Sets the value of the urlColor property.
                     * 
                     */
                    public void setUrlColor(short value) {
                        this.urlColor = value;
                    }

                    /**
                     * Gets the value of the adType property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getAdType() {
                        return adType;
                    }

                    /**
                     * Sets the value of the adType property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setAdType(String value) {
                        this.adType = value;
                    }

                    /**
                     * Gets the value of the borderStyle property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getBorderStyle() {
                        return borderStyle;
                    }

                    /**
                     * Sets the value of the borderStyle property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setBorderStyle(String value) {
                        this.borderStyle = value;
                    }

                    /**
                     * Gets the value of the fontFamily property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFontFamily() {
                        return fontFamily;
                    }

                    /**
                     * Sets the value of the fontFamily property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFontFamily(String value) {
                        this.fontFamily = value;
                    }

                    /**
                     * Gets the value of the fontSize property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFontSize() {
                        return fontSize;
                    }

                    /**
                     * Sets the value of the fontSize property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFontSize(String value) {
                        this.fontSize = value;
                    }

                }

            }

        }

    }

}
