//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.11 at 07:13:58 PM UZT 
//


package https.www_google_com.apis.ads.publisher.v202205;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.www_google_com.apis.ads.publisher.v202205 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.www_google_com.apis.ads.publisher.v202205
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAdUnitsByStatementResponse }
     * 
     */
    public GetAdUnitsByStatementResponse createGetAdUnitsByStatementResponse() {
        return new GetAdUnitsByStatementResponse();
    }

    /**
     * Create an instance of {@link GetAdUnitsByStatementResponse.Rval }
     * 
     */
    public GetAdUnitsByStatementResponse.Rval createGetAdUnitsByStatementResponseRval() {
        return new GetAdUnitsByStatementResponse.Rval();
    }

    /**
     * Create an instance of {@link GetAdUnitsByStatementResponse.Rval.Results }
     * 
     */
    public GetAdUnitsByStatementResponse.Rval.Results createGetAdUnitsByStatementResponseRvalResults() {
        return new GetAdUnitsByStatementResponse.Rval.Results();
    }

    /**
     * Create an instance of {@link GetAdUnitsByStatementResponse.Rval.Results.InheritedAdSenseSettings }
     * 
     */
    public GetAdUnitsByStatementResponse.Rval.Results.InheritedAdSenseSettings createGetAdUnitsByStatementResponseRvalResultsInheritedAdSenseSettings() {
        return new GetAdUnitsByStatementResponse.Rval.Results.InheritedAdSenseSettings();
    }

    /**
     * Create an instance of {@link ResponseHeader }
     * 
     */
    public ResponseHeader createResponseHeader() {
        return new ResponseHeader();
    }

    /**
     * Create an instance of {@link GetAdUnitsByStatementResponse.Rval.Results.InheritedAdSenseSettings.Value }
     * 
     */
    public GetAdUnitsByStatementResponse.Rval.Results.InheritedAdSenseSettings.Value createGetAdUnitsByStatementResponseRvalResultsInheritedAdSenseSettingsValue() {
        return new GetAdUnitsByStatementResponse.Rval.Results.InheritedAdSenseSettings.Value();
    }

}
