//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.11 at 07:13:58 PM UZT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.google.com/apis/ads/publisher/v202205", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.www_google_com.apis.ads.publisher.v202205;
